spring.application.name=crud2-builder
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/test_crud2_builder
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#init 데이터
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#
#spring.thymeleaf.cache=false
#spring.h2.console.settings.web-allow-others=true